In [12]:
import plotly.plotly as py
import plotly.graph_objs as go
import csv

import pandas as pd

In [13]:
# Get Data: this ex will only use part of it (i.e. rows 750-1500)
#df = pd.read_csv('./Datasets/Drought_2014.csv')
drought = "./Datasets/Drought_2014.csv"
drought_df = pd.read_csv(drought)
drought_df

,Rank,Name,All sectors,sd,nodata,0,5,1,15,2,25,3,35,4,45,hist,Agricultural,Domestic,Industrial
0,1,Western Sahara,4.42,0.77,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2240.00,0.00,0.00,4187.00,NaN,-,4.67,-
1,2,Mauritania,3.79,0.56,0.00,213103.00,68.00,0.00,0.00,15015023.00,5311185.00,193063936.00,1029178304.00,27249688.00,257697616.00,NaN,3.76,4.03,4.19
2,3,Niger,3.72,0.80,0.00,0.00,0.00,1018.00,142785.00,7111591.00,410962976.00,308104448.00,563758144.00,30930076.00,344561408.00,NaN,3.58,4.19,3.59
3,4,Senegal,3.65,1.00,0.00,0.00,0.00,0.00,313544768.00,35064292.00,173029264.00,957396.00,1027470272.00,0.00,661242240.00,NaN,3.71,3.10,3.21
4,5,Oman,3.41,0.80,0.00,5934516.00,0.00,106059.00,60064496.00,265336880.00,62856892.00,235582000.00,542186240.00,101497696.00,157366064.00,NaN,3.39,3.46,3.72
5,6,Peru,3.39,1.38,0.00,700552576.00,267940544.00,920185408.00,3133602304.00,455007456.00,2701303552.00,1674152832.00,537297408.00,3263563776.00,6703970304.00,NaN,3.53,2.75,3.20
6,7,Egypt,3.35,0.76,0.00,331971872.00,29458004.00,2703615.00,678048256.00,560444480.00,2022756608.00,44208959488.00,4063433472.00,188638160.00,8666412032.00,NaN,3.33,3.42,3.42
7,8,Namibia,3.30,0.83,0.00,124506.00,12483.00,48276.00,56290.00,62486824.00,72965744.00,74841352.00,79734160.00,6108686.00,43386996.00,NaN,2.93,3.81,3.77
8,9,Qatar,2.94,0.62,0.00,0.00,1697681.00,25737056.00,0.00,181215168.00,0.00,413682816.00,38148560.00,7093097.00,0.00,NaN,2.66,3.19,2.98
9,10,Sudan,2.94,0.78,0.00,0.00,145747.00,676655.00,2211904000.00,4908194304.00,5558996480.00,11672890368.00,1161804800.00,70261200.00,2521998336.00,NaN,2.88,3.20,3.62
10,11,United Arab Emirates,2.92,1.31,0.00,578003200.00,260930752.00,179802752.00,263210592.00,209992192.00,481507040.00,1274178816.00,1140986368.00,1170531968.00,6894871.00,NaN,3.22,2.18,2.67
11,12,Mali,2.90,1.09,0.00,661452.00,218440560.00,319427936.00,233234336.00,1608446208.00,240689616.00,174769744.00,505374240.00,1551335936.00,49723040.00,NaN,3.12,2.48,2.22
12,13,Armenia,2.83,0.33,0.00,0.00,0.00,425753.00,0.00,707530816.00,171300688.00,1570004096.00,0.00,0.00,0.00,NaN,2.83,2.82,2.88
13,14,Jordan,2.80,0.34,0.00,0.00,0.00,0.00,7045952.00,284204.00,1011965440.00,107286304.00,0.00,53435108.00,1428509.00,NaN,2.86,2.69,2.73
14,15,Libya,2.77,1.25,0.00,150249760.00,0.00,33140640.00,1959925248.00,956159872.00,1389480448.00,130112960.00,237400512.00,17548.00,1270322560.00,NaN,2.81,2.50,2.81
15,16,Eritrea,2.73,0.83,0.00,3470655.00,19977950.00,54388732.00,31953492.00,4065217.00,124379400.00,293641824.00,586044.00,0.00,0.00,NaN,2.71,2.91,2.17
16,17,Botswana,2.70,0.47,0.00,0.00,0.00,0.00,22637984.00,5882220.00,155179424.00,27405512.00,12701358.00,1983594.00,1172510.00,NaN,2.40,2.86,2.77
17,18,Ecuador,2.64,1.10,0.00,8441426.00,1760328832.00,3658831360.00,544287040.00,623955456.00,1692477312.00,1088202880.00,6635730432.00,845989376.00,0.00,NaN,2.70,2.40,2.06
18,19,Turkmenistan,2.62,0.58,0.00,42067168.00,28285786.00,116080704.00,5035060224.00,4582809600.00,9152154624.00,927366464.00,4172387840.00,0.00,0.00,NaN,2.64,2.40,2.17
19,20,Iran,2.57,0.52,0.00,60130152.00,193730928.00,2596559360.00,6520094720.00,30129852416.00,29415876608.00,18957328384.00,1017153280.00,586519680.00,0.00,NaN,2.58,2.53,2.53
20,21,Uzbekistan,2.57,0.32,0.00,0.00,0.00,4166051.00,6418867200.00,7768025600.00,45815586816.00,11551300.00,1991863808.00,0.00,0.00,NaN,2.56,2.57,2.64
21,22,Somalia,2.56,0.66,0.00,17840278.00,153024.00,142438256.00,195536464.00,341966080.00,274158112.00,883124224.00,0.00,0.00,0.00,NaN,2.57,2.00,1.63
22,23,Chad,2.54,0.93,0.00,0.00,0.00,18643212.00,228263712.00,37929668.00,49812760.00,218976960.00,32469414.00,4361809.00,24558844.00,NaN,2.60,2.16,2.72
23,24,Afghanistan,2.48,0.49,0.00,0.00,0.00,437920416.00,7652869632.00,4847488512.00,16856516608.00,1613691264.00,1225130240.00,0.00,0.00,NaN,2.48,2.29,2.40
24,25,Pakistan,2.48,0.47,0.00,236487552.00,0.00,569913344.00,20919279616.00,78614020096.00,63376756736.00,14911048704.00,24.00,4383706112.00,0.00,NaN,2.48,2.39,2.40
25,26,Finland,2.46,0.76,0.00,17274570.00,95002512.00,10734357.00,424448192.00,150921264.00,1006207232.00,187079200.00,85778368.00,42491660.00,0.00,NaN,2.33,2.32,2.51
26,27,Tajikistan,2.45,0.21,0.00,0.00,0.00,0.00,181711680.00,5477458944.00,7056955904.00,0.00,0.00,0.00,0.00,NaN,2.44,2.49,2.58
27,28,Kazakhstan,2.43,0.54,0.00,134317728.00,624452672.00,2060690560.00,1937104128.00,12307910656.00,16246602752.00,1430824960.00,328157376.00,66375008.00,19041546.00,NaN,2.48,2.27,2.24
28,29,Syria,2.37,0.50,0.00,121976480.00,0.00,677825088.00,4493064192.00,3395466752.00,8089140224.00,303100352.00,683537920.00,0.00,0.00,NaN,2.38,2.31,2.30
29,30,Kyrgyzstan,2.32,0.24,0.00,0.00,0.00,0.00,1211871488.00,5823776768.00,2980843264.00,0.00,0.00,0.00,0.00,NaN,2.31,2.41,2.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,171,Cyprus,0.15,0.36,0.00,83319576.00,0.00,14495559.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.13,0.26,0.18
171,172,Jamaica,0.02,0.05,0.00,812865600.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.01,0.02,0.02
172,173,Antigua and Barbuda,0.00,0.00,0.00,8026709.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00
173,173,Bahrain,0.00,0.00,0.00,413053888.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00
174,173,Barbados,0.00,0.00,0.00,69750728.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00
175,173,Comoros,0.00,0.00,0.00,11226803.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00
176,173,Dominica,0.00,0.00,0.00,4829325.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,-,0.00,0.00
177,173,Malta,0.00,0.00,0.00,49969988.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00
178,173,Saint Lucia,0.00,0.00,0.00,6852419.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00
179,173,Saint Vincent and the Grenadines,0.00,0.00,0.00,3591320.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,-,0.00,0.00
180,174,Cape Verde,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
181,174,Curacao,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
182,174,Federated States of Micronesia,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
183,174,Fiji,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
184,174,Grenada,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
185,174,Kiribati,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
186,174,Maldives,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
187,174,Marshall Islands,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
188,174,Mauritius,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
189,174,Nauru,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
190,174,Palau,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
191,174,Saint Kitts and Nevis,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
192,174,Samoa,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
193,174,Sao Tome and Principe,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
194,174,Seychelles,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
195,174,Solomon Islands,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
196,174,The Bahamas,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
197,174,Tonga,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
198,174,Tuvalu,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-
199,174,Vanuatu,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-

In [16]:
dat = []
with open('./Chloro_Map/Chloropleth_Asylum_Data.csv', newline='') as csvfile:
    spamreader = csv.reader(csvfile, delimiter=',', quotechar='"')
    for row in spamreader:
        dat.append(row)
        
asylum = pd.DataFrame(data=dat[1:], columns=dat[0])

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xea in position 4023: invalid continuation byte

In [2]:
trace1 = go.Scatter3d(
    x=df['year'][750:1500],
    y=df['continent'][750:1500],
    z=df['pop'][750:1500],
    text=df['country'][750:1500],
    mode='markers',
    marker=dict(
        sizemode='diameter',
        sizeref=750,
        size=df['gdpPercap'][750:1500],
        color = df['lifeExp'][750:1500],
        colorscale = 'Viridis',
        colorbar = dict(title = 'Life<br>Expectancy'),
        line=dict(color='rgb(140, 140, 170)')
    )
)

data=[trace1]

layout=go.Layout(height=800, width=800, title='Examining Population and Life Expectancy Over Time')

fig=go.Figure(data=data, layout=layout)
py.iplot(fig, filename='3DBubble')

KeyError: 'year'